

// USER
// login
POST http://localhost:8000/api/users/login


// ADMIN


// CAR 
###
POST http://localhost:8000/api/admin/register
Content-Type: application/json

{
    "email" : "admin@gmail.com",
    "password" : "123",
}

###
POST http://localhost:8000/api/admin/login
Content-Type: application/json

{
    "email" : "admin@gmail.com",
    "password" : "123",
}



// CAR 
###
GET http://localhost:8000/api/cars


// Ajouter les car
###
POST http://localhost:8000/api/cars
Content-Type: application/json

{
    "Name": "Nmax",
    "Type": "6386130d0f39e3039985d968"
   
}

// RESERVATION
###
//Confirmtion reservation sur email
POST http://localhost:8000/api/Reservation/Confirmer/:Gmail


//Ajouter Reservation 
###

POST http://localhost:8000/api/Reservation
Content-Type: application/json

{
    "UserName": "Ayoub benouahi",
    "Adress": "HAy Moulay rachid khemisset",
    "City": "khemisset",
    "state":"Rabat",
    "Zip":"13525",
    "Country":"Country",
    "Type":"Huv1",
    "Date": 

}

// Aficher Reservation
###
GET http://localhost:8000/api/Reservation

// SUprimer Reservation
###
DELETE http://localhost:8000/api/Reservation/:_id 


// Moudifier Reservation    
###
PUT http://localhost:8000/api/Reservation/:_id


// TYPES

###
//Aficher Les Types De Car
GET http://localhost:8000/api/Type

// Ajouter les Types~
###
POST http://localhost:8000/api/Type
Content-Type: application/json

{
    "Type_Name": "bot5",
    "Date_Creation": "2022-06-06",
    "Prix": "10000",
    "Detalles":["63860fb91be8e42bb37760f6","63860fcb1be8e42bb37760fc"]
   
}



//DETALLES

// Aficher les Detalles
###
GET http://localhost:8000/api/detalles


// Ajouter les Detalles
###

POST http://localhost:8000/api/detalles
Content-Type: application/json

{

    "Keys": "16",
    "Nom_Value": "max",
    "Value": "150"

}
